<?php include('partes/InicioIng.inc.php'); ?>

<div class="row">
    <div class="col px-0">
    <?php include('partes/inicio_breadcrumb.inc.php'); ?>
        <li class="breadcrumb-item"><a href="index.php"tabindex="22">Home</a></li>
        <li class="breadcrumb-item"><a href="historiadance.php"tabindex="23">History of Dance</a></li>
        <li class="breadcrumb-item"><a href="artistasdance.php"tabindex="24">Dance artists</a></li>
        <li class="breadcrumb-item active">Dance News</li>
    <?php include('partes/fim_breadcrumb.inc.php'); ?>
    </div>
</div>
<!--Início da página -->

<div class = "container">
<div class = "row">
<div class = "col-lg-12">
<h1 tabindex = "25" id = "content"> How did electronic music come about </h1>
</div>
<div class = "col-12">
<p tabindex = "26">
The history of electronic music began in 1948, with the broadcasting of clothing concerts by the broadcaster - French television, influenced by the French Pierre Schaeffer who created or produces concrete music, where a composition was made from discs generated by discs. discs, as well as including sound manipulation by varying the speed or reading direction of recordings.At the same time or the German Werner Meyer-Eppler realized experiments with sound, while speculating about his possible use of music . In 1951, Meyer-Eppler and composer Herbert Eimert joined Robert Beyer and created the first electronic electronic music studio. Although we use recording and assembly techniques similar to those performed at the RTF studios in Paris, these techniques were applied only to children of electronic origin generated by electric oscillators.
</p>
</div>
    
    <div class = "col-lg-4">
                    <img src = "img/avicci.png" alt = "image of a barefoot blond man sitting on a sofa playing guitar in a room with two windows in the back and a lamp" class = "img-fluid" tabindex = "27" />
                </div>
                <div class = "col-lg-8">
                    <p tabindex = "28">
                        Its primary purpose was the interaction between people and raising consciousness (an escape from reality) through various art forms. Electronic music played a key role in such parties as it provides through repetitive and progressive beats a hypnotic effect on participants, sometimes enhanced by the use of narcotics. From the development of the electronic style in the 1980s, events were held in rural areas for people gathering, dancing and ecstasy use. Similarly, the 1960s preached the gathering of people and the use of drugs (especially LSD) as a form of raising consciousness. Even with the media's negative reaction to such a culture the style was developing, resulting in a lifestyle for the participants.
                       
                    </p>
                </div>
    
    
    
    
<div class = "col-lg-12">
                    <p tabindex = "29">
                  Electronic music began to become popular with the emergence of digital synthesizers, later with samplers, but the boom occurred with personal computers that have audio capabilities and the ease of setting up a home - studio, making it possible to emulate the functionalities. of musical instruments or synthesizers through the creation, manipulation and virtual presentation of sound.
                    </p>
                </div>
                <div class = "row" class = "row">
<a class="sr-only sr-only-focusable text-dark" href="#inicio" tabindex="30"> Return to the navigation menu </a>
                    <div class = "col-lg-8">
                        <p tabindex = "31">
                         The popularization of these instruments has led to the emergence of various artists who have devoted themselves exclusively to electronic music, appearing in various styles, such as industrial music, dance electronic music, which branched out into House, Trance, Acid House, Techno, Hardcore Techno, Breakbeat, Drum n Bass, Ambient, Tribal, among many others. Electronic music can be summarized as “music produced from non-instruments, or from instruments adapted to produce electricity-modified sound”.
                        </p>


                    </div>
                    
                    
                    
                    
                    
                    
                    
                    <div class = "col-lg-4">
                        <img src = "img/ma.jpg" alt = "image of dj marshmello, the image shows a man dressed in white wearing a white mask in which his eyes are shaped like marshmellows, and in the background a bridge with the sky blue "class =" img-fluid "tabindex =" 32 "/>
                    </div>
                    <div class = "col-lg-12">
                        <p tabindex = "33">
However, in Brazil a new style of electronic music called Electronic Live Music has emerged, which is the insertion and modification of sound by electricity at the very moment the music is being propagated, that is, the music is being modified at the same time. being performed live. An important element in the development of dance electronic music was the development of raves. Such electronic music parties began as a reaction to popular music trends, nightclub culture, and commercial radio.
                        </p>


                    </div>

                      
                </div>
                <div class = "row" class = "row">
                    <div class = "col-12 text-center">
                     <h1 class = "text-dark" tabindex = "34"> Read also </h1>
                    </div>
                    <div class = "col-sm-12 col-md-6 col-lg-6 text-center">
                        
                            <img src = "img/ed.jpg" alt = "the image shows a red-haired man dressed in a black shirt and a xadrex blouse playing a guitar with his mouth open and in the background a microphone and a stage panel like those who can be seen on stages where singers perform. "class =" img-fluid "tabindex =" 35 ">
                            <h2 tabindex = "36"> Ed Sheeran and Justin Bieber are in Brazil's most searched hits list via Shazam </h2>
                            <p tabindex = "37"> Ed Sheeran and Justin Bieber are in Brazil's most searched hits list via Shazam </p>
                       
                    </div>
                    
                    
                    
                    
                    
                    <div class = "col-sm-12 col-md-6 col-lg-6 text-center">
                      
                            <img src = "img/ca.jpg" alt = "the image shows a blond man with a beard and mustache wearing a red-eyed glasses and some trees in the background." class = "img-fluid" tabindex = "38">
                            <h2 tabindex = "39"> Calvin Harris is the highest paid DJ in the world for the fifth year in a row </h2>
                            <p tabindex = "40"> Harris, who recently released the song "One Kiss" with Dua Lipa, is closely followed by the duo The Chainsmokers. "Closer" hitmakers made $ 45.5 million last year. </p>
                       
                    </div>
                </div>
      <a class="sr-only sr-only-focusable text-dark" href="#inicio" tabindex="41"> Return to the navigation menu </a>
</div>


<!--Fim da página-->
<?php include('partes/fiming.inc.php'); ?>